version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
      - POSTGRES_USER=${PROD_DB_USER}
      - POSTGRES_PASSWORD=${PROD_DB_PASSWORD}
      - POSTGRES_DB=your_db_name  # Replace with your DB name
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - iot-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com # Replace with your admin email
      - PGADMIN_DEFAULT_PASSWORD=admin # Replace with your admin password
    ports:
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - iot-network
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"  # RabbitMQ Management Plugin Web UI
      - "5672:5672"    # RabbitMQ messaging port
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
