server:
  port: ${PRO_SERVER_PORT}

  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: youralias

spring:
  application:
    name: iot-web-server

  datasource:
    url: jdbc:postgresql://${PROD_DB_URL}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate.format_sql: true

  rabbitmq:
    host: ${PROD_RABBITMQ_HOST}
    port: ${PROD_RABBITMQ_PORT}
    username: ${PROD_RABBITMQ_USER}
    password: ${PROD_RABBITMQ_PASSWORD}
    virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10

logging:
  file:
    name: mylog.log
  level:
    root: info
